syntax = "proto3";

package routes;

import "models/models.proto";
import "shared/shared.proto";

message GetLobbiesResponse {
  repeated models.LobbyData lobbies = 1;
}

message GetLobbyResponse {
  optional models.LobbyData lobby = 1;
}

message CreateLobbyRequest {
  string lobby_name = 1;
}

message CreateLobbyResponse {
  string code = 1;
}

message GetLobbyDetailsResponse {
  optional models.DetailedLobbyData lobby_details = 1;
}

message ChangeLobbySettingsRequest {
  models.LobbySettings settings = 1;
}

message KickPlayerRequest {
  int32 user_id = 1;
}

message ChangePlayerIDRequest {
  int32 user_id = 1;
  shared.PlayerIDs player_id = 2;
}
