syntax = "proto3";

package routes;

import "models/models.proto";
import "shared/shared.proto";

message GetLobbiesResponse {
  repeated models.LobbyData lobbies = 1;
}

message GetLobbyResponse {
  optional models.LobbyData lobby = 1;
}

message CreateLobbyResponse {
  string code = 1;
}

message GetLobbyDetailsResponse {
  optional models.DetailedLobbyData lobby_details = 1;
}

message ResponseLobbyMember {
  string id = 1;
  string user_id = 2;
  string username = 3;
  shared.PlayerTypes player_type = 4;
  shared.PlayerIDs player_id = 5;
}

message GetLobbyMembersRequest {
  string code = 1;
}


message GetLobbyMembersResponse {
  repeated ResponseLobbyMember members = 1; 
}
