syntax = "proto3";

package ws;

import "shared/shared.proto";

// Request / client packets

message GameInsertTile {
  int32 column = 1;
}

enum GameActions {
  GAME_ACTIONS_UNSPECIFIED = 0;
  GAME_ACTIONS_INIT = 1;
  GAME_ACTIONS_INSERT_TILE = 2;
}

message GamePacket {
  GameActions action = 1;
  oneof data {
    GameInsertTile insert_tile = 2;
  }
}

// Response / server packets

message PartialUser {
  string username = 1;
}

message Token {
  int32 row = 1;
  int32 column = 2;
  shared.PlayerIDs playerID = 3;
}

message GameEnd {
  Token token = 1;
  oneof winner {
    PartialUser user = 2;
    bool draw = 3;
  }
}

message GameMove {
  Token token = 1;
  shared.GameBoard board = 2;
  shared.PlayerIDs turn = 3;
}

enum GameResponses {
  GAME_RESPONSES_UNSPECIFIED = 0;
  GAME_RESPONSES_ERROR = 1;
  GAME_RESPONSES_MOVE = 2;
  GAME_RESPONSES_END = 3;
}

message GameResponsePacket {
  GameResponses response = 1;
  oneof data {
    shared.CodedError error = 2;
    GameMove move = 3;
    GameEnd end = 4;
  }
}
