syntax = "proto3";

package ws;

import "shared/shared.proto";

// Request / client packets

message GameInsertTile {
  int32 column = 1;
}

enum GameActions {
  GAME_ACTIONS_UNSPECIFIED = 0;
  GAME_ACTIONS_INSERT_TILE = 1;
  GAME_ACTIONS_FORFEIT = 2;
}

message GamePacket {
  GameActions action = 1;
  oneof data {
    GameInsertTile insert_tile = 2;
  }
}

// Response / server packets

message PartialUser {
  int32 id = 1;
  string username = 2;
}

enum GameEndTypes {
  GAME_END_TYPES_UNSPECIFIED = 0;
  GAME_END_TYPES_STANDARD_WIN = 1;
  GAME_END_TYPES_FORFEITED = 2;
  GAME_END_TYPES_DRAW = 3;
}

message GameEnd {
  optional int32 row = 1;
  optional int32 column = 2;
  GameEndTypes endType = 3;
  oneof winner {
    PartialUser user = 4;
  }
}

message GameMove {
  int32 row = 1;
  int32 column = 2;
  shared.GameBoard board = 3;
  shared.PlayerIDs turn = 4;
}

enum GameResponses {
  GAME_RESPONSES_UNSPECIFIED = 0;
  GAME_RESPONSES_ERROR = 1;
  GAME_RESPONSES_MOVE = 2;
  GAME_RESPONSES_END = 3;
}

message GameResponsePacket {
  GameResponses response = 1;
  oneof data {
    shared.CodedError error = 2;
    GameMove move = 3;
    GameEnd end = 4;
  }
}
