syntax = "proto3";

package ws;

import "models/user.proto";
import "shared/shared.proto";

// Request / client packets

message GameInsertToken {
  int32 column = 1;
  models.TokenTypes token_type = 2;
}

enum GameActions {
  GAME_ACTIONS_UNSPECIFIED = 0;
  GAME_ACTIONS_INSERT_TOKEN = 1;
  GAME_ACTIONS_FORFEIT = 2;
}

message GamePacket {
  GameActions action = 1;
  oneof data {
    GameInsertToken insert_token = 2;
  }
}

// Response / server packets

enum GameEndTypes {
  GAME_END_TYPES_UNSPECIFIED = 0;
  GAME_END_TYPES_STANDARD_WIN = 1;
  GAME_END_TYPES_FORFEITED = 2;
  GAME_END_TYPES_DRAW = 3;
}

message Tile {
  int32 row = 1;
  int32 column = 2;
  optional models.Token token = 3;
}

message GameInit {
  shared.PlayerIDs player_id = 1;
}

message GameMove {
  Tile tile = 1;
  shared.GameBoard board = 2;
  shared.PlayerIDs turn = 3;
  repeated Tile changeTiles = 4;
}

message GameEnd {
  GameEndTypes endType = 1;
  optional Tile tile = 2;
  optional models.PartialUser winner = 3;
  optional models.PartialUser loser = 4;
  shared.GameBoard board = 5;
  repeated Tile changeTiles = 6;
}

enum GameResponses {
  GAME_RESPONSES_UNSPECIFIED = 0;
  GAME_RESPONSES_ERROR = 1;
  GAME_RESPONSES_INIT = 2;
  GAME_RESPONSES_MOVE = 3;
  GAME_RESPONSES_END = 4;
}

message GameResponsePacket {
  GameResponses response = 1;
  oneof data {
    shared.CodedError error = 2;
    GameInit init = 3;
    GameMove move = 4;
    GameEnd end = 5;
  }
}
