syntax = "proto3";

package ws;

import 'models/models.proto';

enum LobbyResponses {
  LOBBY_RESPONSES_UNSPECIFIED = 0;
  LOBBY_RESPONSES_ERROR = 1;
  LOBBY_RESPONSES_JOIN = 2;
  LOBBY_RESPONSES_LEAVE = 3;
  LOBBY_RESPONSES_CHANGE_PLAYER = 4;
  LOBBY_RESPONSES_START_GAME = 5;
  LOBBY_RESPONSES_HOST_LEFT = 6;
  LOBBY_RESPONSES_SETTINGS_CHANGED = 7;
}

message LobbyJoin {
  repeated models.DetailedLobbyMemberData users = 1;
}

message LobbyLeave {
  repeated models.DetailedLobbyMemberData users = 1;
}

message LobbyChangePlayer {
  repeated models.DetailedLobbyMemberData users = 1;
}

message LobbyResponsePacket {
  LobbyResponses response = 1;
  oneof data {
    shared.CodedError error = 2;
    LobbyJoin join = 3;
    LobbyLeave leave = 4;
    LobbyChangePlayer changePlayer = 5;
    models.LobbySettings settings = 6;
  }
}
