FROM node:20 as base
WORKDIR /connect-4-backend

RUN apt-get update && apt-get install -y python3 make g++

COPY package.json package-lock.json ./
RUN npm ci --build-from-source
RUN npm i -g tsx

COPY . .

CMD ["tsx", "./app.ts"]
