syntax = "proto3";

package models;

import 'models/models.proto';

message Lobby {
  string code = 1;
  string lobby_name = 2;
}

message LobbyData {
  string code = 1;
  string lobby_name = 2;
  int32 member_count = 3;
  bool has_game = 4;
}

message LobbySettings {
  int32 turn_time = 1;
}

message DetailedLobbyData {
  string code = 1;
  string lobby_name = 2;
  int32 member_count = 3;
  bool has_game = 4;
  models.DetailedLobbyMemberData host = 5;
  repeated models.DetailedLobbyMemberData lobby_members = 6;
  LobbySettings settings = 7;
}
