syntax = "proto3";

package shared;

enum ErrorCodes {
  ERROR_CODES_UNSPECIFIED = 0;
  ERROR_CODES_SERVER_ERROR = 1;
  ERROR_CODES_BAD_LOBBY_CODE = 2;
  ERROR_CODES_BAD_DATA = 3;
  ERROR_CODES_BAD_TURN = 4;
  ERROR_CODES_BAD_USER = 5;
  ERROR_CODES_BAD_NAME = 6;
  ERROR_CODES_UNAUTHORISED = 7;
  ERROR_CODES_ALREADY_JOINED = 8;
  ERROR_CODES_NOT_A_MEMBER = 9;
  ERROR_CODES_LOBBY_CREATE_FAIL = 10;
  ERROR_CODES_GAME_LOCKED = 11;
  ERROR_CODES_GAME_EXPIRED = 12;
  ERROR_CODES_GAME_ALREADY_EXISTS = 13;
  ERROR_CODES_DOESNT_EXIST = 14;
  ERROR_CODES_USER_ALREADY_EXISTS = 15;
}

message CodedError {
  ErrorCodes code = 1;
  optional string error = 2;
}
